# Generated by Django 5.0.7 on 2024-09-26 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('academia_id', models.AutoField(primary_key=True, serialize=False)),
                ('academia_endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('academia_telefone', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('academia_horario', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('paciente_id', models.AutoField(primary_key=True, serialize=False)),
                ('paciente_nome', models.CharField(blank=True, max_length=100, null=True)),
                ('paciente_cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('paciente_rg', models.CharField(blank=True, max_length=11, null=True)),
                ('paciente_telefone', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('paciente_endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('paciente_bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('paciente_cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('paciente_peso', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('paciente_altura', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('medico_id', models.AutoField(primary_key=True, serialize=False)),
                ('medico_nome', models.CharField(blank=True, max_length=20, null=True)),
                ('medico_crm', models.CharField(blank=True, max_length=20, null=True)),
                ('medico_telefone', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('medico_endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('medico_cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('medico_estado', models.CharField(blank=True, max_length=2, null=True)),
                ('medico_especialidade', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('pagamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('pagamento_pix', models.CharField(blank=True, max_length=50, null=True)),
                ('pagamento_cartao_credito', models.CharField(blank=True, max_length=50, null=True)),
                ('pagamento_cartao_debito', models.CharField(blank=True, max_length=50, null=True)),
                ('pagamento_transferencia', models.CharField(blank=True, max_length=50, null=True)),
                ('pagamento_boleto', models.CharField(blank=True, max_length=50, null=True)),
                ('pagamento_comprovante', models.CharField(blank=True, max_length=50, null=True)),
                ('pagamento_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_login', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario_senha', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('dieta_paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.paciente')),
                ('dieta_tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('dieta_descricao', models.TextField(blank=True, null=True)),
                ('dieta_data_inicio', models.DateField()),
                ('dieta_data_fim', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicacao',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.paciente')),
                ('medicacao_tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('medicacao_descricao', models.TextField(blank=True, null=True)),
                ('medicacao_data_inicio', models.DateField()),
                ('medicacao_data_fim', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('receita_paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.paciente')),
                ('receita_medicacao', models.CharField(blank=True, max_length=200, null=True)),
                ('receita_descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('especialidade_medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.medico')),
                ('especialidade_medico_crm', models.CharField(blank=True, max_length=20, null=True)),
                ('especialidade_tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('especialidade_descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_data_agendamento', models.DateField()),
                ('agenda_hora_agendamento', models.TimeField()),
                ('agenda_especialidade', models.CharField(max_length=20)),
                ('agenda_observacoes', models.TextField(blank=True, null=True)),
                ('agenda_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.paciente')),
                ('agenda_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.medico')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoPaciente',
            fields=[
                ('historico_paciente_id', models.AutoField(primary_key=True, serialize=False)),
                ('historico_paciente_dados', models.JSONField()),
                ('historico_paciente_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.paciente')),
            ],
        ),
    ]
